name: Build and Test

on: [push, pull_request] # Trigger the workflow on push or pull request events

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository # Step to checkout the code from the repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK # Step to set up the .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build # Step to build the C# program
      run: dotnet build HelloWorld.cs

    - name: Test # Step to run the C# program
      run: dotnet run HelloWorld.cs

    - name: Verify Output # Step to verify if the output is "Hello, World!"
      run: |
        output=$(dotnet run HelloWorld.cs)
        if [ "$output" != "Hello, World!" ]; then
          echo "Test failed: Output was not 'Hello, World!'"
          exit 1
        else
          echo "Test passed: Output is 'Hello, World!'"
        fi
